# Generated by Django 6.0.6 on 2026-07-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('person', 'คน (Person)'), ('car', 'รถยนต์ (Car)')], max_length=20, verbose_name='ประเภทวัตถุ')),
                ('confidence', models.FloatField(verbose_name='ความแม่นยำ (%)')),
                ('latitude', models.FloatField(verbose_name='ละติจูดวัตถุ')),
                ('longitude', models.FloatField(verbose_name='ลองจิจูดวัตถุ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่ตรวจเจอ')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_sn', models.CharField(default='M4E', max_length=50, verbose_name='Serial Number โดรน')),
                ('latitude', models.FloatField(verbose_name='ละติจูด')),
                ('longitude', models.FloatField(verbose_name='ลองจิจูด')),
                ('altitude', models.FloatField(verbose_name='ความสูง (เมตร)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่บันทึก')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
