# Generated by Django 6.0.6 on 2026-08-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrylog',
            name='battery_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='แบตเตอรี่ (%)'),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='flight_mode_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสโหมดการบิน (ดิบจาก DJI mode_code)'),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='gps_satellites',
            field=models.IntegerField(blank=True, null=True, verbose_name='จำนวนดาวเทียม GPS'),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='heading',
            field=models.FloatField(blank=True, null=True, verbose_name='ทิศหัวโดรน (องศา, 0=เหนือ)'),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='home_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='ระยะห่างจากจุด Home (m)'),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='horizontal_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='ความเร็วแนวนอน (m/s)'),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='vertical_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='ความเร็วแนวตั้ง (m/s)'),
        ),
    ]
