# Generated by Django 6.0.6 on 2026-08-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_telemetrylog_battery_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightControlEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_sn', models.CharField(default='M4E', max_length=50, verbose_name='Serial Number โดรน')),
                ('event_type', models.CharField(choices=[('requested', 'ขอสิทธิ์ควบคุม'), ('granted', 'ได้รับสิทธิ์ควบคุม'), ('denied', 'ถูกปฏิเสธ/หมดเวลา'), ('released', 'ปล่อยสิทธิ์ควบคุม (สั่งเอง)'), ('watchdog_release', 'ปล่อยสิทธิ์ควบคุมอัตโนมัติ (watchdog/disconnect)'), ('emergency_stop', 'สั่งหยุดฉุกเฉิน'), ('error', 'ข้อผิดพลาด')], max_length=20, verbose_name='ประเภทเหตุการณ์')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่เกิดเหตุการณ์')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
