"""
Django settings for drone_system project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# โหลด .env ที่อยู่สูงขึ้นไป 1 ชั้น (โฟลเดอร์นอกสุด)
load_dotenv(os.path.join(BASE_DIR.parent, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%lt1hzqvc(o$lsnb4!$@5!a(3o&c_^2af=7bq+nk42=1@3pqk*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# ดึงค่ามาเตรียมใช้ใน Django
DJI_APP_ID = os.getenv('DJI_APP_ID')
DJI_APP_KEY = os.getenv('DJI_APP_KEY')
DJI_APP_LICENSE = os.getenv('DJI_APP_LICENSE')
SERVER_IP = os.getenv('SERVER_IP', '127.0.0.1')
DJANGO_PORT = int(os.getenv('DJANGO_PORT', '8006'))

DJI_WORKSPACE_ID = os.getenv('DJI_WORKSPACE_ID', '')
DJI_PLATFORM_NAME = os.getenv('DJI_PLATFORM_NAME', 'Drone AI Platform')
DJI_WORKSPACE_NAME = os.getenv('DJI_WORKSPACE_NAME', 'Default Workspace')
DJI_WORKSPACE_DESC = os.getenv('DJI_WORKSPACE_DESC', '')

MQTT_PORT = int(os.getenv('MQTT_PORT', '1883'))
MQTT_PUBLIC_PORT = int(os.getenv('MQTT_PUBLIC_PORT', os.getenv('MQTT_PORT', '1883')))
MQTT_USER = os.getenv('MQTT_USER', 'admin')
MQTT_PASSWORD = os.getenv('MQTT_PASSWORD', 'admin1234')
MQTT_USE_ANONYMOUS = os.getenv('MQTT_USE_ANONYMOUS', 'true').lower() == 'true'
PILOT_USERNAME = os.getenv('PILOT_USERNAME', 'pilot')
PILOT_PASSWORD = os.getenv('PILOT_PASSWORD', 'pilot123')
MQTT_WS_PORT = int(os.getenv('MQTT_WS_PORT', '8083'))
MQTT_WS_USE_GATEWAY = os.getenv('MQTT_WS_USE_GATEWAY', 'true').lower() == 'true'
MQTT_WS_GATEWAY_PATH = os.getenv('MQTT_WS_GATEWAY_PATH', '/mqtt')
DJANGO_INTERNAL_PORT = int(os.getenv('DJANGO_INTERNAL_PORT', os.getenv('DJANGO_PORT', '8007')))

RTMP_PORT = int(os.getenv('RTMP_PORT', '1935'))
SRS_HTTP_PORT = int(os.getenv('SRS_HTTP_PORT', '8085'))
SRS_API_PORT = int(os.getenv('SRS_API_PORT', '1985'))
RTMP_APP = os.getenv('RTMP_APP', 'live')
RTMP_STREAM_KEY = os.getenv('RTMP_STREAM_KEY', 'drone')

TELEMETRY_STALE_SECONDS = int(os.getenv('TELEMETRY_STALE_SECONDS', '30'))

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'app_core',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    #'app_core.middleware.RequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'drone_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drone_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
